### ISSUE TITLE
Uncaught TypeError: auth.requestPasswordChange is not a function

### ISSUE THREAD

**Issue by beebase** [nhost/nhost-js-sdk#63]
Is this method supposed to work? 
(I assume this method sends the user an email with a link to create a new password?)
![image](https://user-images.githubusercontent.com/446089/110626650-4ad31f80-81a1-11eb-8d5b-3e404e6db79c.png)

I'm getting this error in the browser:
` Uncaught TypeError: auth.requestPasswordChange is not a function`

**Comment by beebase** [comment]
@elitan 
I was on 2.3.4 so I upgraded to latest (3.1.0)
HBP (server) is also on latest.

Error mentioned above is  gone but I'm getting a 404 from server now.
Maybe I'm overlooking a setting on the server side?

`POST https://....com/auth/change-password/request 404`

```
// client method
  const requestNewPassword = () => {
    auth.requestPasswordChange(sEmail)
  }
```

serverlog:

```
POST /auth/change-password/request 404 60 - 34.909 ms
GET /healthz 200 2 - 3.181 ms
OPTIONS /auth/change-password/request 204 0 - 0.739 ms
Error: Not Found
    at /app/dist/routes/index.js:22:26
    ..... {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 404,
    payload: { statusCode: 404, error: 'Not Found', message: 'Not Found' },
    headers: {}
  }
}
```

docker-compose config
```
 hasura-backend-plus:
    image: nhost/hasura-backend-plus:latest
    ports:
      - '3008:3000'
    environment:
      ...
      ...
      EMAILS_ENABLE: "true"
    volumes:
      - 'hbp_data:/app/custom'
volumes:
  db_data:
  hbp_data:
  minio_data:

```
